### ISSUE TITLE
Security Tooling: Is OSTG the right place for security tool and security process guidance?

### ISSUE THREAD

**Issue by SecOctoBear** [Open-Source-Compliance/Sharing-creates-value#64]
Dear Tooling Community,

at SAP we are working on an Open Source strategy, incorporating enhancements to the established Open Source Vulnerability Management. We aim to achieve qualities assurance (security and maintenance) and proactive prevention of vulnerabilities by supporting tools:
- Automated risk rating for developers indicating the “well-being” of a community and its artifacts
- Hardening of a component based on the usage in the application
- Monitoring external threat landscape for an increasing risk of public CVE advisories
- Regular update notifications to the developers

We would like to share and exchange with the security community. I see that Tooling Group primarily focus on license but picks up some security-related tool guidance. ClearlySecure community may be an alternative but a) their focus seems to be on particular projects and b) the project seems to be in a very early state.
Would Tooling Group be the right place to bring up the discussion?

Michael

**Comment by OliverFendt** [comment]
Hi Michael,

this sounds very interesting. Especially the tools which you might be working on. The "Component Metadata Repository" and the "Proejct Metadata Repository" could have a coonection to these tools and external sources in order to povide a complete "white box view " components and proejcts.
Our long term goal is to have:

- OSS – Compliance processes and tools
- OSS – Contribution processes and tools
- Security vulnerability management 
- Export control and customs classification
- OSS – selection process (quality, healthiness, maintainability, etc - KPIs) 

fully integrated in the DevOPs cycle

So your effort an input is highly welcome and appreciated

**Comment by OliverFendt** [comment]
Looking forward to receive your contributions

**Comment by SecOctoBear** [comment]
@OliverFendt I will come back with proposals shortly. Though, do not expect before November due to next week's OSS EU.
